game:
  name: "werewolf"

players:

  - name: "Alice"
    role: "werewolf"
    strategy: "naive"
    model: "deepseek-chat"

  - name: "Bobby"
    role: "werewolf"
    strategy: "naive"
    model: "deepseek-chat"

  - name: "Cacey"
    role: "werewolf"
    strategy: "naive"
    model: "deepseek-chat"

  - name: "Danny"
    role: "seer"
    strategy: "naive"
    model: "glm-4"

  - name: "Eason"
    role: "witch"
    strategy: "naive"
    model: "glm-4"
  
  - name: "Fried"
    role: "hunter"
    strategy: "naive"
    model: "glm-4"

  - name: "Gabbi"
    role: "villager"
    strategy: "naive"
    model: "glm-4"

  - name: "Harry"
    role: "villager"
    strategy: "naive"
    model: "glm-4"
  
  - name: "Isaac"
    role: "villager"
    strategy: "naive"
    model: "glm-4"