game:
  name: "werewolf"
#  剧本是 首先 werewolf 攻击 (danny, isaac, isaac), issac 被witch救了, witch毒死了 alice, 投票投死了Harry，然后 晚上 werewolf攻击hunter, hunter开枪打死了 cacey

players:
  - name: "Alice"
    role: "werewolf"
    strategy: "replay"
    replay: 
      - action: "attack"
        target: "Danny"
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Danny"

  - name: "Bob"
    role: "werewolf"
    strategy: "replay"
    replay: 
      - action: "attack"
        target: "Isaac"
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Danny"
      - action: "vote"
        vote: "Harry"
      - action: "attack"
        target: "Fried"

  - name: "Cacey"
    role: "werewolf"
    strategy: "replay"
    replay: 
      - action: "attack"
        target: "Isaac"
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Danny"
      - action: "vote"
        vote: "Harry"
      - action: "attack"
        target: "Fried"

  - name: "Danny"
    role: "seer"
    strategy: "replay"
    replay: 
      - action: "check"
        check: "Bob"
      - action: "discuss"
        words: "I am a seer, and alice is wolf"
      - action: "vote"
        vote: "Alice"
      - action: "vote"
        vote: "Harry"

  - name: "Eason"
    role: "witch"
    strategy: "replay"
    replay: 
      - action: "heal"
        heal: "Isaac"
      - action: "poison"
        target: "Alice"
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Alice"
      - action: "vote"
        vote: "Harry"
      
  - name: "Fried"
    role: "hunter"
    strategy: "replay"
    replay: 
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Alice"
      - action: "vote"
        vote: "Harry"
      - action: "hunt"
        hunt: "Cacey"
      

  - name: "Gabbi"
    role: "villager"
    strategy: "replay"
    replay: 
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Alice"
      - action: "vote"
        vote: "Bob"

  - name: "Harry"
    role: "villager"
    strategy: "replay"
    replay: 
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Alice"
      - action: "vote"
        vote: "Bob"
  
  - name: "Isaac"
    role: "villager"
    strategy: "replay"
    replay: 
      - action: "discuss"
        words: "I am a good person"
      - action: "vote"
        vote: "Alice"
      - action: "vote"
        vote: "Bob"