game:
  name: "skyteam"

players:
  - name: "Alice"
    role: "pilot"
    strategy: "naive"
    model: "deepseek-chat"

  - name: "Bobby"
    role: "copilot"
    strategy: "naive"
    model: "deepseek-chat"
