
game:
  name: "werewolf"

players:
  - name: "Alice"
    role: "werewolf"
    strategy: "naive"
    model: "01-ai/Yi-1.5-34B-Chat-16K"
    
  - name: "Bobby"
    role: "werewolf"
    strategy: "naive"
    model: "01-ai/Yi-1.5-34B-Chat-16K"

  - name: "Cacey"
    role: "werewolf"
    strategy: "naive"
    model: "01-ai/Yi-1.5-34B-Chat-16K"

  - name: "Danny"
    role: "seer"
    strategy: "naive"
    model: "Qwen/Qwen1.5-14B-Chat"

  - name: "Eason"
    role: "witch"
    strategy: "naive"
    model: "Qwen/Qwen1.5-14B-Chat"
  
  - name: "Fried"
    role: "hunter"
    strategy: "naive"
    model: "Qwen/Qwen1.5-14B-Chat"

  - name: "Gabbi"
    role: "villager"
    strategy: "naive"
    model: "Qwen/Qwen1.5-14B-Chat"

  - name: "Harry"
    role: "villager"
    strategy: "naive"
    model: "Qwen/Qwen1.5-14B-Chat"
  
  - name: "Isaac"
    role: "villager"
    strategy: "naive"
    model: "Qwen/Qwen1.5-14B-Chat"
