game:
  name: "azul"

players:

  - name: "Alice"
    role: "player1"
    strategy: "naive"
    model: "deepseek-chat"

  - name: "Bobby"
    role: "player2"
    strategy: "naive"
    model: "deepseek-chat"
